### ISSUE TITLE
Question: ROS2 control of Cyberdog

### ISSUE THREAD

**Issue by tomasz-lewicki** [MiRoboticsLab/cyberdog_ros2#114]
Hi! 

I'm using the robot and so far I'm really impressed with it, awesome work!
I was able to get [sample gRPC](https://github.com/Karlsx/CyberDog_Ctrl) code running, and build some sample apps on top of that.

I'm curious whether there are any simple examples of operating using ROS2 directly?  If not, do you have any recommendations on how to approach it? So far, the best idea I have is to instantiate `Cyberdog_app` Node and go from there.

Best,
Tomasz

**Comment by homalozoa** [comment]
Hi Tomasz. Thanks for your attention! There are many ways to control cyberdog, like using gRPC, ROS 2 messages, LCM, etc. We use gRPC as a very high level to control the robot, because it support so many programming languages. But ROS messages is only support C++ and Python, if you do not install third party RCL implementation. LCM is only designed for locomotion controling, we use it because MIT mini cheetah using it. The locomotion is built on their exellent work.

You can do more things by using ROS messages, but I'm refactoring the whole project recently. Hince many APIs will change in Future. APIs are including all controlling cmds, sensor datas, output devices cmds.

But if you want to control robot only. Please refer to https://github.com/MiRoboticsLab/cyberdog_ros2/tree/devel/cyberdog_interfaces/motion_msgs and https://github.com/MiRoboticsLab/cyberdog_ros2/blob/devel/cyberdog_managers/README_EN.md . I forgot writing English README for interfaces, you could translate it with Google Translation. If you have any problem, please let me know. And post in this issue. Thank you.

**Comment by homalozoa** [comment]
By the way. As we chatted at Telegram. Publishing the IP of the HOST device as a string to topic "ip_notify" is the best way to active cyberdog with gRPC. The HOST device could be your mobile phone, or your PC in the same local area network or wireless local area network.

**Comment by hno3kyoz** [comment]
https://github.com/MiRoboticsLab/cyberdog_ros2/blob/devel/cyberdog_managers/README_EN.md

**Comment by hno3kyoz** [comment]
The url:
https://github.com/MiRoboticsLab/cyberdog_ros2/blob/devel/cyberdog_managers/README_EN.md 
was changed to 
https://github.com/MiRoboticsLab/cyberdog_ros2/blob/devel/cyberdog_decision/README_EN.md
